name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: DoozyX/clang-format-lint-action@master
        with:
          source: "."
          extensions: "h,cpp,c"
          clangFormatVersion: 12
          inplace: False
