name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: App compilation
      run: |
        make
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.GITHUB_REPOSITORY }}-${{ steps.slug.outputs.sha8 }}
        path: ['*.elf', '*.ELF']
